UKForeignOffice/lists

- config/postgresql-local.conf
- docker-compose.yml
Add custom `postgresql-local.conf` and enable statistics collectors.
Add docker-compose pghero service.
> Local postgres config to enable statistics collectors

- README.md
- docker-compose.yml
- package.json
- src/form-runner/forms-json/lawyers.json
- src/server/__tests__/lawyers-list.test.ts
- src/server/controllers/lists/helpers.ts
- src/server/controllers/lists/lawyers.ts
- src/server/controllers/lists/types.ts
- src/server/models/__tests__/listItem.test.ts
- src/server/models/listItem.ts
- src/server/views/lists/partials/answers-box.html
- src/server/views/lists/partials/question-pro-bono.html
Improve README documentation.
Update Lawyer JSON form.
> Lawyer pro bono question

- package.json
- src/server/controllers/dashboard/dashboard.ts
- src/server/models/__tests__/audit.test.ts
- src/server/models/__tests__/listItem.test.ts
- src/server/models/audit.ts
- src/server/models/db/seed-data/helpers.ts
- src/server/models/list.ts
- src/server/models/listItem.ts
- src/server/models/types.ts
- src/server/routes/__tests__/dashboard.test.ts
- src/server/routes/dashboard.ts
Audit list item approve and publish events and tech debt tests
> Audit list item approve and publish events

- src/form-runner/forms-json/covid-test-providers.json
Deprecate opening time question.
Deprecate out of hours results question.
Some hint text adjustments.
> COVID-19 test providers form journey adjustments 

- src/form-runner/forms-json/covid-test-providers.json
- src/form-runner/install-form-runner.sh
- src/server/models/listItem.ts
- src/server/views/includes/phase-banner.html
Refactor covid-test-providers form journey turnaround values.
Refactor covid-test-provider data ingestion due to turnaround values changes.
Change application phase banner to `Beta`.
> Upgrade form runner dependency

- src/form-runner/forms-json/covid-test-providers.json
- src/server/models/db/__tests__/helpers.test.ts
- src/server/models/db/helpers.ts
- src/server/models/helpers.ts
- src/server/routes/development.ts
Deprecate temporary development routes and respective helper functions. 
Test populateDb helper.
> Cleanup dev routes

- package.json
- src/server/components/formRunner/helpers.ts
This fix bug where form-runner stops responding
> Form runner listen to stdout

- .circleci/config.yml
- src/server/models/listItem.ts
- src/server/views/lists/partials/questions/question-practice-area.njk
The areas of law filters now do something
> fix: lawyer fields of law filtering

- src/server/views/dashboard/lists-items.njk
- src/server/views/dashboard/macros.njk
> feat: updated alert messages

- README.md
- docs/README.md
- docs/connecting-to-test-db.md
- docs/getting-started.md
- docs/google-tag-manager.md
- docs/release-management.md
- docs/scripts.md
- package.json
> chore: documentation

- cypress.json
- cypress/integration/apply.feature
- cypress/support/step_definitions/apply/i_decare.js
- cypress/support/step_definitions/apply/i_enter_my_address.js
- cypress/support/step_definitions/apply/i_enter_my_email_with_string.js
- cypress/support/step_definitions/apply/i_enter_my_regions.js
- cypress/support/step_definitions/apply/i_enter_my_regulators.js
- cypress/support/step_definitions/apply/i_enter_my_website_string.js
- cypress/support/step_definitions/apply/i_want_to_apply_to_be_added_as_a_string.js
- cypress/support/step_definitions/apply/legal.js
- cypress/support/step_definitions/apply/my_company_is_string.js
- cypress/support/step_definitions/apply/my_given_names_are_string.js
- cypress/support/step_definitions/common/i_select_the_option_string.js
- package-lock.json
- package.json
- webpack.config.js
- webpack - default to environment variable if NODE_ENV isn't detected 
- smoke test scenario for apply to be added to the 'Find a lawyer abroad' service
> test: smoke tests for application

- .circleci/config.yml
- src/server/views/dashboard/macros.njk
Issue exists when marking a lawyer as published or approved from the management section.  Note, the first record was able to be updated but subsequent records could not be so check record 2 onwards when testing.
> Fixed bug for publishing and approving lawyers

- .circleci/config.yml
- src/server/components/lists/helpers.ts
- src/server/views/cookies/cookie-banner.njk
- src/server/views/cookies/cookies-page.njk
- src/server/views/dashboard/lists-edit.njk
- src/server/views/dashboard/users-edit.njk
- src/server/views/lists/partials/covid-test-providers/covid-test-providers-notice.njk
- src/server/views/lists/partials/questions/question-covid-disclaimer.njk
- src/server/views/login.njk
A couple of fixes to address the following issues:
- Unable to add users (email addresses) to a List in the Management section
- Unable to set permissions for a user in the Management section
- _csrf parameter populated in the URL query string on each question page starting with the country selection
- Reverted circle ci config changes when setting up VPN
> Fix for updating Lists and Users & minor CSRF token fix

- docker/apply/forms-json/funeral-directors.json
- src/server/__tests__/covid-test-providers.test.ts
- src/server/__tests__/lawyers-list.test.ts
- src/server/components/sitemap/__tests__/controllers.ts
- src/server/components/sitemap/controllers.ts
- src/server/models/listItem/__tests__/listItem.test.ts
- src/server/models/listItem/geoHelpers.ts
- src/server/views/lists/partials/answers-box.njk
- case sensitivity issue when adding country (ingest post controller / apply journey)
- removed case sensitivity displaying country in answers box (find journey)
- added FDs to sitemap
- removed unnecessary path to error page in country next links in FD json
> Fixed case sensitivity issue when adding country plus misc other changes

- src/server/components/dashboard/listsItems/getViewModel.ts
The purpose of this PR is to fix the missing public email in the lawyers list
This ticket has now been updated to always display the public email in list management:
https://user-images.githubusercontent.com/1377253/183978371-7a384c54-f847-4c18-8f74-c628021137f7.mp4
> fix: issue with missing public email

- docs/README.md
- docs/connecting-to-test-db.md
- docs/fixing-local-data-issues.md
- docs/getting-started.md
- docs/helpful-urls.md
The purpose of this pull request is to update the documentation in the repo to match my experience with setting up the list application.
And to include some useful tips for future developers.
> docs: update documentation

- src/server/__tests__/covid-test-providers.test.ts
- src/server/__tests__/lawyers-list.test.ts
- src/server/components/auth/express-session.ts
- src/server/views/lists/partials/answers-box.njk
- src/server/views/lists/partials/funeral-directors/macros.njk
- src/server/views/lists/partials/lawyers/macros.njk
The purpose of this ticket is to update the session timeout from 1 hour to 4 and also to change a few layout things with the find listing page for funeral directors and lawyers.
Ticket: https://trello.com/c/QXxgSELk/1306-list-management-funeral-directors-make-time-out-period-4hrs
> List management - Funeral directors - make time out period 4hrs [READY TO MERGE]

- docker/apply/forms-json/funeral-directors.json
- docker/apply/forms-json/lawyers.json
- docker/apply/forms-json/translators-interpreters.json
- docker/apply/views/help/privacy.html
- src/server/components/lists/controllers/index.ts
- src/server/components/lists/questionnaire.ts
- src/server/services/govuk-notify.ts
- src/server/services/metadata.ts
- src/server/views/dashboard/list-item-confirm-changes.njk
- src/server/views/includes/disclaimer.njk
- src/server/views/lists/partials/questions/question-contact-insurance.njk
- src/server/views/lists/partials/questions/question-country.njk
- src/server/views/lists/partials/questions/question-insurance.njk
- src/server/views/lists/partials/questions/question-repatriation.njk
- src/server/views/lists/partials/questions/question-services-provided.njk
- src/server/views/lists/partials/translators-interpreters/translators-interpreters-notice.njk
- src/server/views/lists/partials/translators-interpreters/translators-interpreters-results-list.njk
Changes included in this PR:
* https://trello.com/c/4b5EVZl5/1436-find-translators-journey-minor-content-changes
* https://trello.com/c/L6nIEpxe/1167-find-apply-funeral-directors-change-deceased-wording
* https://trello.com/c/fdiVzvkf/1441-list-management-all-edit-request-formatting
> Miscellaneous content changes

- docker/apply/views/summary.html
- src/server/views/lists/partials/questions/question-region.njk
- Content change to region question as per design: https://trello.com/c/4b5EVZl5/1436-find-translators-journey-minor-content-changes
- Fix to retain line breaks in summary page of apply journey per this card: https://trello.com/c/fdiVzvkf/1441-list-management-all-edit-request-formatting
> Content change to region question in find journey & change to summary page in apply journey

- docker/apply/forms-json/covid-test-providers.json
- docker/apply/forms-json/find-translators-interpreters.json
- docker/apply/forms-json/funeral-directors.json
- src/server/models/db/migrations/20220916112245_remove_macedonia/migration.sql
- src/server/services/metadata.ts
Replace Macedonia with North Macedonia
Trello ticket: https://trello.com/c/QkBuutzp/1289-list-management-delete-macedonia
> chore: update macedonia

- src/server/components/lists/questionnaire.ts
Related to trello card: https://trello.com/c/4b5EVZl5/1436-find-translators-journey-minor-content-changes
> changed hint text to language question page in find journey

- .prettierrc.json
- docker/apply/views/help/terms-and-conditions.html
- src/server/views/help/terms-and-conditions.njk
The purpose of this ticket is to update the copy terms and conditions and conditions page.
Ticket: https://trello.com/c/KbRgikD8/1367-update-tcs-for-all-the-apply-services
> chore: update copy on T & C's page

- src/server/views/dashboard/lists-items.njk
The purpose of this PR is to change the copy of the top section for the list management page to include the policy guidance.
> chore: update policy guidance

- cypress/e2e/funeral-directors/list-management.feature
- cypress/e2e/management-list-item-actions.feature
- src/server/components/dashboard/helpers.ts
- src/server/components/dashboard/listsItems/controllers.ts
- src/server/components/dashboard/listsItems/helpers.ts
- src/server/components/dashboard/listsItems/types.ts
- src/server/views/dashboard/list-item-confirm-changes.njk
- src/server/views/dashboard/list-item-confirm-pin.njk
- src/server/views/dashboard/list-item-confirm-publish.njk
- src/server/views/dashboard/list-item-confirm-remove.njk
- src/server/views/dashboard/list-item-confirm-unpublish.njk
- src/server/views/dashboard/list-item-confirm-update.njk
- src/server/views/dashboard/macros.njk
The purpose of this PR is to update the radio buttons on the list management page for providers that have not been published but have made an update.
> chore: update radio button for publish

- package-lock.json
#474 
this PR was missing an updated package-lock file which caused an issue here https://github.com/UKForeignOffice/lists/actions/runs/3554008041.
> fix: lockfile for prisma update

- src/server/components/dashboard/__tests__/controllers.test.ts
- src/server/components/dashboard/annualReview/controllers.ts
- src/server/components/dashboard/annualReview/helpers.ts
- src/server/views/dashboard/lists-edit-annual-review-date-confirm.njk
- src/server/views/dashboard/lists-edit-annual-review-date.njk
- src/server/views/dashboard/lists-edit.njk
- src/server/views/dashboard/lists-new.njk
The purpose of this PR is to:
- improve the logic around setting restrictions around the annual review date
- update the copy in certain places as suggested by Neil
https://user-images.githubusercontent.com/1377253/207604420-06bcfb3b-2db4-4c6d-94e0-80d80057ef48.mp4
> chore: update logic for date calculation

- src/server/components/dashboard/listsItems/controllers.development.ts
- src/server/components/dashboard/listsItems/itemsRouter.ts
- src/server/views/dashboard/lists-edit-dev.njk
- src/server/views/dashboard/lists-edit.njk
- src/server/views/dashboard/macros.njk
- hidden endpoint /:listId/development
- accessible to admins only
- allows adjustment of annual review notification dates
> Time endpoint helper

- src/server/models/listItem/summary.helpers.ts
if OUT_WITH_PROVIDER, render slightly different text - but still filters the same as other with provider
> feat: add out for annual review tag

- src/server/components/dashboard/listsItems/getViewModel.ts
- src/server/components/formRunner/helpers.ts
- src/server/models/listItem/listItem.ts
used the merged updatedJsonData (merges jsonData + updatedJsonData). `makeAddressGeoLocationString` is expecting all address props
> fix: address updates

- cypress/e2e/annual-review/confirmation.feature
- cypress/support/step_definitions/annual-review/the_list_is_in_annual_review.js
- cypress/support/step_definitions/dashboard/there_is_a_list_with_all_states.js
- src/server/components/annual-review/controller.ts
- src/server/components/lists/controllers/ingest/__tests__/ingestPutController.test.ts
- src/server/components/lists/controllers/ingest/ingestPutController.ts
- src/server/models/db/schema.prisma
- src/server/models/listItem/listItem.ts
- src/server/models/listItem/listItemEvent.ts
- add reference to event so events are searchable by annual review
- search by reference 
- check if CHECK_ANNUAL_REVIEW event has been issued for a given reference
> fix: add reference to event so events are searchable by annual review

- src/server/components/dashboard/listsItems/getViewModel.ts
add organisationName to the base fields. (Always displays)
> fix: display org name

- src/server/components/dashboard/listsItems/controllers.ts
- src/server/components/dashboard/listsItems/item/update/actionHandlers/publish.ts
- src/server/components/dashboard/listsItems/item/update/actionHandlers/requestChanges.ts
- src/server/components/dashboard/listsItems/item/update/actionHandlers/update.ts
- src/server/components/dashboard/listsItems/item/update/controllers.confirm.ts
- src/server/components/formRunner/funeralDirectors.ts
- src/server/components/formRunner/helpers.ts
- src/server/components/formRunner/lawyers.ts
- src/server/components/formRunner/translatorsInterpreters.ts
- src/server/models/db/migrations/20230209130000_migrate_to_updated_json_data.sql/migration.sql
- src/server/models/listItem/__tests__/listItem.test.ts
- src/server/models/listItem/listItem.ts
- src/server/models/listItem/providers/deserialisers/types.ts
- src/server/views/lists/partials/funeral-directors/macros.njk
- src/server/views/lists/partials/lawyers/macros.njk
- src/server/views/lists/partials/translators-interpreters/macros.njk
No longer need to unpublish a list item to request edits.  When the list item is in PUBLISHED or CHECK_ANNUAL_REVIEW statuses, you can now see the "request edits" option.
> Enabled request changes button for published list items

- cypress/e2e/funeral-directors/list-management.feature
- cypress/e2e/management-list-item-actions.feature
- cypress/support/step_definitions/common/I_see_the_input_string.js
- cypress/support/step_definitions/dashboard/list_settings/i_do_not_see_string_on_the_page.js
- cypress/support/step_definitions/dashboard/listitems/the_textarea_should_show_if_i_click_the_request_changes_radio_button.js
- src/server/components/dashboard/listsItems/controllers.ts
- src/server/components/dashboard/listsItems/item/update/actionHandlers/archive.ts
- src/server/components/dashboard/listsItems/item/update/actionHandlers/index.ts
- src/server/components/dashboard/listsItems/item/update/actionHandlers/update.ts
- src/server/components/dashboard/listsItems/item/update/controllers.confirm.ts
- src/server/components/dashboard/listsItems/item/update/types.ts
- src/server/components/dashboard/listsItems/itemsRouter.ts
- src/server/models/listItem/listItem.ts
- src/server/models/listItem/listItemEvent.ts
- src/server/models/listItem/summary.ts
- src/server/views/dashboard/list-item-confirm/archive.njk
- src/server/views/dashboard/lists-item.njk
- src/server/views/dashboard/macros.njk
- src/server/views/layout.njk
This is pretty much an updated version of this old PR https://github.com/UKForeignOffice/lists/pull/505
Link to Trello ticket: https://trello.com/c/DGzWTJX0/1515-add-new-action-archive-to-list-items
> feat: add archive feature to list items

- docs/README.md
- docs/update-prod-data.md
The purpose of this PR is to add documentation on how to get data from prod and put it onto the dev environment.
Ticket in Trello: https://trello.com/c/8yNRapPN/1573-change-dev-environment-emails-to-default-to-list-managementcautionyourblastcom
> docs: update docs with data for changing dev data

- docker/apply/views/help/privacy.html
The purpose of this PR is to update the privacy policy for the apply journey.
Link to Trello ticket: https://trello.com/c/NjTgXHgf/1428-privacy-policy-changes
> chore: update privacy policy

- src/server/components/auth/helpers.ts
- src/server/components/dashboard/controllers.ts
- src/server/components/dashboard/listsItems/itemsRouter.ts
- src/server/views/dashboard/lists-edit.njk
Reverts UKForeignOffice/lists#605
> chore (revert): Reverting "allow users with list role to edit annual review" 

- cypress/e2e/management-user-roles.feature
- cypress/e2e/management-users.feature
- cypress/support/step_definitions/dashboard/list_settings/i_enter_string_in_the_email_input.js
- src/client/styles/styles.scss
- src/server/components/dashboard/controllers.ts
- src/server/views/dashboard/lists-edit.njk
- src/server/views/dashboard/lists-new.njk
- src/server/views/dashboard/partials/new-user-banner.njk
- src/server/views/dashboard/users-edit.njk
- src/server/views/dashboard/users-list.njk
- src/server/views/includes/header-list-mgmt.njk
Everything now says super admin 😆
> chore: copy changes from users to admins

- src/client/styles/styles.scss
- src/server/views/lists/results-page.njk
Update style of related content section on find results page
> style(styles.scss): add blue section break style

- .circleci/config.yml
Bug details: https://github.com/cypress-io/code-coverage/issues/667
> Add specific cypress version to fix 12.15.0 bug

- docker/apply/forms-json/translators-interpreters.json
- src/server/services/metadata.ts
> chore: add montenegrin to countries

- docker/apply/forms-json/covid-test-providers.json
- docker/apply/forms-json/funeral-directors.json
- docker/apply/forms-json/lawyers.json
- docker/apply/forms-json/provider-complaint.json
- docker/apply/forms-json/provider-contact.json
- docker/apply/forms-json/translators-interpreters.json
- src/server/models/db/migrations/20230814130516_update_name_of_gambia/migration.sql
- src/server/services/metadata.ts
update country name from "Gambia" to "The Gambia" for consistency
update URL for The Gambia funeral directors list
> chore(forms-json): update country name from "Gambia" to "The Gambia"

- .github/workflows/release.yml
#Description
The purpose of this PR is to upgrade the version of node in the CI to support a newer version of Prisma
> chore: update node version to 16 in the setup node env

- src/server/components/auth/__tests__/controllers.test.ts
- src/server/components/auth/controllers.ts
- src/server/utils/validation.ts
`success: true` page was being rendered even though it should not have been.
> fix: invalid email address error

- docker/apply/Dockerfile
Updating the crown logo and the latest formrunner image
> feat: FCDO-1785 - Updating to the latest formrunner image
