src/server/views/lists/partials/covid-test-providers/macros.njk

Display available tests information outside details section.
Move email information inside details section.
Deprecate opening times information.

Covid19 test provider list results adjustments

---

src/form-runner/forms-json/covid-test-providers.json

Telephone number inputs are using text inputs intead of phone number.
Minor ccopy change to certificates translation question.
Add website option to results format lists.

Adjustments to covid-test-provider form journey

---

src/form-runner/forms-json/covid-test-providers.json
src/form-runner/install-form-runner.sh
src/server/models/listItem.ts
src/server/models/types.ts
src/server/services/form-runner/types.ts
src/server/views/lists/partials/covid-test-providers/macros.njk

Add `Additional email address` and `Additional phone number` fields for form journey.
Refactor ingestion code to include two new fields.
Extend covid test providers list item with addtional email and telephone.
Upgrade form runner dependency.

Covid19 test providers `Additional email address` and `Additional phone number` fields

---

package.json
src/form-runner/install-form-runner.sh
src/server/__tests__/cookies.test.ts
src/server/controllers/cookies/cookies.ts
src/server/controllers/cookies/index.ts
src/server/middlewares/views.ts
src/server/routes/cookies.ts
src/server/views/cookies/cookie-banner.html
src/server/views/layout.html

Adjust cookies policy to base64 encode cookie value so form-runner can parse it.
Upgrade form-runner dependency.
Minor refactoring.

Adjust cookies policy bug with form-runner

---

package-lock.json
package.json
webpack.config.js

Pages which were using the Webpack generated `main.css` file were not loading up the correct fonts. This fix corrects the Webpack config in order to load those fonts.

fix: correct webpack config to load fonts

---

package-lock.json
package.json

A tag for `v1.16.3` already existed but the version was never bumped up in `package.json`. This change fixes that so that the versions all line up

chore: bump version to align with GitHub tags

---

src/server/models/__tests__/listItem.test.ts
src/server/models/listItem.ts

The check to see if a country has any items in a list did not take into account publish state so it would stop redirecting if there were pending applications. This fix stops that from happening and will only allow you to continue your search if a country + list combination has published items.
Fixes: https://trello.com/c/DpkbZC4D/907-update-pilot-countries-in-live-find-a

fix: check publish and approval states when checking if list is populated

---

src/server/components/lists/controllers.ts

lawyers use publicEmailAddress instead of contactEmailAddress, so detecting a little drift here. I've just put in another `??` statement, but we should come up with a better way of resolving this when we next add a list

fix: mapping for alternative email address for lawyers

---

src/server/views/includes/disclaimer.njk
src/server/views/lists/partials/questions/question-covid-disclaimer.njk

previously was linking to terms-conditions where it should've been terms-and-conditions

fix: fix link to terms-and-conditions in disclaimer

---

src/server/models/listItem/__tests__/geoHelpers.test.ts
src/server/models/listItem/geoHelpers.ts
src/server/services/location.ts

constructs the string by adding the values to an array, filtering (removing falsey values, like undefined, empty string), then iterating over them and trimming the whitespace either side `.trim()`

fix: resolve issue with makeAddressGeoLocationString adding too much whitespace

---

docker/apply/forms-json/funeral-directors.json
docker/apply/forms-json/lawyers.json
docker/apply/forms-json/translators-interpreters.json
src/server/views/lists/partials/questions/question-country.njk

The purpose of this ticket is to add the "Select country or territory" text to the Find and Apply journeys of this project
https://trello.com/c/j1EprHte/1089-reword-which-country-question-in-apply-and-find

chore: update country text on apply journeys

---

docker/apply/forms-json/lawyers.json

The purpose of this PR is to make the postcode field optional for the apply process for lawyers
Ticket: https://trello.com/c/hVBWvUlL/1130-lawyers-apply-journey-make-postcode-optional

chore: make postocde field optinal for lawyers

---

docker/apply/forms-shelf/find-translators-interpreters.json
src/server/__tests__/covid-test-providers.test.ts
src/server/__tests__/lawyers-list.test.ts
src/server/components/lists/controllers/index.ts
src/server/components/lists/helpers.ts
src/server/components/lists/searches/covid-test-provider.ts
src/server/components/lists/searches/funeral-directors.ts
src/server/components/lists/searches/lawyers.ts
src/server/services/metadata.ts
src/server/views/dashboard/lists-items.njk
src/server/views/lists/partials/funeral-directors/funeral-directors-results-list.njk
src/server/views/lists/partials/lawyers/lawyers-results-list.njk
src/server/views/lists/results-page.njk

Two issues reported since the release of the infrastructure changes that included a fix to permit “northern Cyprus” (lowercase n) country URL parameter by removing the case conversion done when validating the country.  In both scenarios the ListItems are queried to check if at least one record is published.
1. when the country url parameter is lowercase the listsPostController is no longer converting the case and it’s being passed in directly from the URL string (after validating that the country exists).
2. when the serviceType url parameter is hyphenated it, once again, it’s passed into the query but the ListItem.jsonData.type field is stored as camel case.
1. Access https://find-a-professional-service-abroad.service.csd.fcdo.gov.uk/find?country=croatia&serviceType=funeral-directors …

Ensure case insensitive country parameters

---

src/server/components/lists/controllers/ingest/ingestPostController.ts
src/server/models/listItem/__tests__/listItem.test.ts
src/server/models/listItem/providers/helpers.ts

The purpose of this PR is to make sure that when an email is sent out to a lawyer(or another profession) requesting a change to their listing, the email is sent to their **PRIVATE** email account and not their **PUBLIC** one.
Ticket: https://trello.com/c/kPMU9v3A/1299-list-management-request-edit-not-sending-to-admin-email
This only applies to lawyers who have both a public and private email in their account.
As I am not able to test this end-to-end locally:
---
I created a console log to see what the function that fetches the email address is outputting:
---
As you will see in [this pull request](https://github.com/UKForeignOffice/lists/pull/429), this specific listing has both a public and private email. It's just not showing in the second screenshot because that fix is on PR #429 and …

fix: incorrect email with change request

---

src/client/styles/styles.scss
src/server/views/dashboard/dashboard.njk
src/server/views/dashboard/lists-item.njk
src/server/views/dashboard/macros.njk

The purpose of this PR is to add a back button to the bottom of the list management page
Ticket: https://trello.com/c/8awKrp25/1360-all-list-management-add-a-back-button-in-list-item-details-page
_NOTE: No designed have been provided for this ticket so I've sort of made things up. I have informed Anna_
https://user-images.githubusercontent.com/1377253/182887296-bc426368-4c15-4a0d-be4e-ff82ff20cb6b.mp4
https://user-images.githubusercontent.com/1377253/184906049-f78c7501-b205-4fbf-979f-6ce2a8e3e114.mp4

chore: add back button for list managment details

---

src/server/components/dashboard/listsItems/controllers.ts
src/server/components/dashboard/listsItems/listItemsIndexController.ts
src/server/views/dashboard/list-item-confirm-changes.njk
src/server/views/dashboard/lists-item.njk
src/server/views/dashboard/macros.njk

The purpose of this ticket is to allow users to see the information they've typed in, after requesting changes , then pressing the back button.
This ticket also adds a back button to the top of the request changes page.
Ticket: https://trello.com/c/ljH69Snw/1401-list-management-build-a-back-button-and-or-cancel-to-let-users-edit-the-change-request-box
https://user-images.githubusercontent.com/1377253/186893203-b1c5f583-1b2d-482d-a439-5ea9e370c9be.mp4

chore: persist change request text on cancellation

---

src/server/views/lists/partials/funeral-directors/macros.njk
src/server/views/lists/partials/lawyers/macros.njk
src/server/views/lists/partials/translators-interpreters/macros.njk

The purpose of this pull request is to show public emails if they exist or show the private email address
Trello ticket: https://trello.com/c/synPjNkb/1507-%F0%9F%9A%A8-p1-investigation-russia-funeral-list-publishing-private-funeral-director-content-in-error

fix: show public emails if they exist

---

docker/apply/forms-json/translators-interpreters.json

The purpose of this PR is the remove the duplicate page for translating in the sworn journey for interpreters. This should make the data in the DB a bit cleaner.

chore: remove duplicate page for sworn journey

---

src/server/components/dashboard/listsItems/controllers.ts
src/server/components/lists/controllers/ingest/ingestPutController.ts
src/server/models/db/migrations/20221125163439_allow_cascading_deletes/migration.sql
src/server/models/db/schema.prisma
src/server/models/listItem/__tests__/summary.helpers.test.ts
src/server/models/listItem/listItem.ts
src/server/models/listItem/listItemEvent.ts
src/server/models/listItem/summary.helpers.ts
src/server/models/listItem/summary.ts
src/server/services/location.ts

- ensuring `check edits` has a higher "priority" than `removed by post`
- https://trello.com/c/8osLTPDj/1518-annual-review-testing-making-something-a-favourite-changes-its-publishing-status
- resolve issue with publishing. updatedJsonData was being destructured but should've been `{ updatedJsonData }`. 
- https://trello.com/c/XKjb8THz/1519-annual-review-testing-sending-things-for-review-or-publishing-doesnt-always-change-the-status

fix: change priority of "check edits" and "removed by post" vs "requested edits"

---

.github/workflows/release.yml
docs/release-management.md
package.json

- update release.yml
- GitHub actions will only run the version on the main branch, so it has to be updated here, even though we're bumping an older version.
- update semantic-release config in package.json
- docs

chore: add support for maintenance branch releases

---

.github/workflows/release.yml
package.json
src/server/components/dashboard/listsItems/getViewModel.ts
src/server/components/dashboard/listsItems/helpers.ts

see #528 
Currently, the answers for "Are you a certified or sworn translator" and "Are you a sworn interpreter" are not being displayed in the dashboard for post (even though the user has been asked to update their details and have now answered the question), if the applicant applied before the new question was introduced. 
- add swornTranslation and swornInterpretation to ViewModel
- if `listItem.jsonData.swornTranslation` or `listItem.jsonData.swornTranslation` is null (i.e. user answered before v1.46.1), display the updated value from `listItem.jsonData.updatedJsonData.swornTranslation`)

fix: correctly render sworn data for dashboard 

---

.circleci/config.yml
cypress/support/step_definitions/dashboard/there_is_a_list_with_all_states.js
src/scheduler/batch/__tests__/helpers.test.ts
src/scheduler/batch/__tests__/main.test.ts
src/scheduler/batch/helpers.ts
src/scheduler/batch/main.ts
src/scheduler/workers/main.ts
src/server/components/annual-review/controller.ts
src/server/models/audit.ts
src/server/models/db/prisma-client.ts
src/server/models/listItem/listItem.ts
src/server/views/dashboard/macros.njk

This PR includes a number of fixes for the annual review process that are outlined below:
- Fixed bug that prevented subsequent lists from being processed if the preceding list contained no list items
- Fixed milestone date comparison that prevented emails being sent to providers
- Fixed next annual review date validation in annual review confirmation controller
- Added annual helper endpoint to update annual review milestone dates that can help with testing

Multiple fixes for the annual review process

---

src/scheduler/batch/__tests__/helpers.test.ts
src/scheduler/batch/__tests__/main.test.ts
src/scheduler/batch/helpers.ts
src/server/components/dashboard/annualReview/helpers.keyDates.ts
src/server/components/dashboard/listsItems/controllers.development.ts
src/server/models/types.ts

Refactored the List.jsonData.currentAnnualReview.keyDates.unpublished key to reflect ONE_WEEK, ONE_DAY and UNPUBLISH apply to both posts and providers.

Refactored unpublish key dates

---

docker/apply/forms-json/covid-test-providers.json
docker/apply/forms-json/find-translators-interpreters.json
docker/apply/forms-json/funeral-directors.json
docker/apply/forms-json/lawyers.json
docker/apply/forms-json/translators-interpreters.json
src/server/services/metadata.ts

The purpose of this PR is to make it possible for user to apply and find their details if they've applied in countries like Kosovo and Somaliland.
Previously the country codes for these countries were incorrect therefore making it difficult for them to be located by the AWS Location services. This PR aims to fix that.
Link to ticket in Trello: https://trello.com/c/VhiQbLN2/1429-add-somaliland-and-kosovo-to-list-of-countries

fix: add ISO code for Kosovo and Somaliland

---

docker/apply/forms-json/covid-test-providers.json
docker/apply/forms-json/find-translators-interpreters.json
docker/apply/forms-json/funeral-directors.json
docker/apply/forms-json/lawyers.json
docker/apply/forms-json/translators-interpreters.json
src/server/services/metadata.ts

AWS Location Services will only accept ISO-3166-alpha-3 codes

fix: add iso compatible codes for Kosovo and Somaliland

---

Dockerfile
package.json

The purpose of this PR is to change the image of NodeJS in Docker to a version that is supported.
NodeJS v14 is only supported up until June 2023, so we will have to upgrade to 16 at some point soon.
Link to ticket in Trello: https://trello.com/c/MsfxOQr8/1601-high-fcdo-014-2-1-inf-000153-outdated-and-unsupported-base-image

feat: upgrade Docker image to the latest version of Node 14

---

docker/apply/Dockerfile
docker/apply/forms-json/funeral-directors.json
docker/apply/forms-json/lawyers.json
docker/apply/forms-json/translators-interpreters.json
src/server/components/development/router.ts
src/server/views/includes/phase-banner.njk
src/server/views/lists/partials/funeral-directors/funeral-directors-notice.njk
src/server/views/lists/partials/lawyers/lawyers-notice.njk
src/server/views/lists/partials/translators-interpreters/translators-interpreters-notice.njk

The purpose of this ticket is to change the feedback links on all the apply journeys (apart form the covid one).
Link to Trello ticket: https://trello.com/c/2od9XQQr/1636-change-feedback-link-on-all-find-a-professional-journeys

chore: make feedback link updates to start pages

---

src/server/components/lists/searches/translators-interpreters.ts
src/server/views/lists/partials/translators-interpreters/translators-interpreters-results-list.njk

The purpose of this pull request is to update the `translators-interpreters.ts` file to improve the readability of the page title.
This commit changes the `formattedService` variable to use "interpreter" in lowercase and "and" instead of "or" when both an interpreter and a translator are present. This makes the page title more consistent, clear, and easier to read.

refactor(translators-interpreters.ts): for scenario where both interpreter and translator

---

src/server/views/lists/partials/funeral-directors/funeral-directors-results-list.njk
src/server/views/lists/partials/lawyers/lawyers-results-list.njk
src/server/views/lists/partials/translators-interpreters/translators-interpreters-results-list.njk

The purpose of this PR is to change the copy on the results page for find so user know links will open in a new tab.

fix(lists): update links to service providers' websites and improve feedback message

---

docker/apply/forms-json/translators-interpreters.json
src/server/models/listItem/providers/deserialisers/TranslatorInterpreter.deserialiser.ts

The addressCountry information is used to populate the country for application forms. Without it the translators form won't work.

fix: add address country to translators

---

src/scheduler/workers/processListsBeforeAndDuringStart/govukNotify.ts
src/scheduler/workers/processListsBeforeAndDuringStart/main.ts
src/server/components/annual-review/controller.ts
src/server/components/auth/__tests__/controllers.test.ts
src/server/models/listItem/providers/TranslatorsInterpreters.ts
src/server/views/annual-review/declaration.njk
src/server/views/lists/partials/lawyers/macros.njk
src/shared/getNotifyClient.ts

**Summary**
This pull request includes the following updates and fixes:
1. User Declaration for Annual Review
Updated the user declaration process to have a declaration per list, not just for lawyers. Previously, the lawyer declaration was displayed for all users.
2. Fix Annual Review Emails
Corrected the issue where annual review emails were being sent to posts without properly checking the response. This caused the emails to appear as failures, preventing their insertion into the audit table and resulting in repeated attempts the next day.
3. Remove Formatting on Lawyer Contact Details
Removed formatting from lawyer contact details, ensuring that the lawyer's name is displayed as entered. This allows for adjustments to be made via the admin dashboard.

feat: Update annual-review declaration

---

docker/apply/forms-json/covid-test-providers.json
docker/apply/forms-json/funeral-directors.json
docker/apply/forms-json/lawyers.json
docker/apply/forms-json/translators-interpreters.json
package-lock.json
package.json
src/server/components/dashboard/helpers.ts
src/server/components/lists/router.ts
src/server/components/lists/routes.ts
src/server/views/timeout.njk
src/types.d.ts

chore(deps): upgrade axios and resolve security advisories
- Upgraded axios from 0.30.1 → 1.12.0 • Updated imports to use CJS build for Jest compatibility • Added TypeScript shim for axios/dist/node/axios.cjs
- Added package.json overrides for: • semver (>=7.5.4) – ReDoS fix • braces (>=3.0.3) – uncontrolled resource consumption • cookie (>=0.7.0) – OOB chars in cookie name/path/domain • tmp (>=0.2.4) – symlink write vulnerability
These changes patch transitive dependencies without forcing breaking upgrades to commitlint, jest-extended, csurf or commitizen.

Application patching
